### ISSUE TITLE
Expected identifier; 'template' is a keyword in Objective-C++

### ISSUE THREAD

**Issue by zycio** [birkir/react-native-carplay#103]
Here is an error: "Expected identifier; 'template' is a keyword in Objective-C++"
https://github.com/birkir/react-native-carplay/blob/c656d6f000d721c818d0afb3f93898bd158f9321/ios/RNCPStore.h#L14

You should change this line:
"- (NSString*) setTemplate:(NSString*)templateId template:(CPTemplate*)template;"
to e.g.:
"- (NSString*) setTemplate:(NSString*)templateId template:(CPTemplate*)templ;"

**Comment by brightsider** [comment]
@birkir hello, can you fix it?

**Comment by yevheniionipko** [comment]
- (NSString*) setTemplate:(NSString*)templateId template:(CPTemplate*)template; 
change to 
- (NSString*) setTemplate:(NSString*)templateId templ:(CPTemplate*)templ;

and change parameter when call setTemplate...
