### ISSUE TITLE
Back button appears on root template if it's a list

### ISSUE THREAD

**Issue by gavrichards** [birkir/react-native-carplay#104]
If you set your root template as list template, you will see a "Back" button at the top, even though there is no where to go back to. Pressing the button does nothing.

This is caused by [these lines in RNCarPlay.m](https://github.com/birkir/react-native-carplay/blob/078550988f2faf46164a92963fbe5a2d1da1f63d/ios/RNCarPlay.m#L151), specifically adding a back button to list templates:
```
CPBarButton *backButton = [[CPBarButton alloc] initWithTitle:@" Back" handler:^(CPBarButton * _Nonnull barButton) {
    [self sendEventWithName:@"backButtonPressed" body:@{@"templateId":templateId}];
    [self popTemplate:false];
}];
[listTemplate setBackButton:backButton];
```

If you comment these lines out, the back button disappears.

It would make sense either for the back button to be an option for the template, or to be removed when the template is mounted as the root.

**Comment by birkir** [comment]
You can now pass `backButtonHidden` flag to disable the back button.
