### ISSUE TITLE
First responder issue on react native alert

### ISSUE THREAD

**Issue by s-maxx** [birkir/react-native-carplay#107]
Hi and thanks for all your work on this repo ! I'm kinda new to swift, so sorry in advance for my ignorance, but it seems that implementing the scene delegates (PhoneScene, as explained in  #85 ) breaks the alerts in react native ... I get the following error:

```[View] First responder issue detected: non-key window attempting reload - allowing due to manual keyboard (first responder window is <UIWindow: 0x125723dc0; frame = (0 0; 375 812); autoresize = W+H; gestureRecognizers = <NSArray: 0x282a29740>; layer = <UIWindowLayer: 0x2829fcf90>>, key window is <UIWindow: 0x123f11a60; frame = (0 0; 375 812); gestureRecognizers = <NSArray: 0x2829d7150>; layer = <UIWindowLayer: 0x2829d6ee0>>)```

I've tried upgrading to the latest RN 0.70.6, with no success.

Does anyone has the same issue ? Or not ? Does anyone know how to fix this ? thanks a lot :) !

**Comment by s-maxx** [comment]
Well I'm surprised no one else has experienced this here, but apparently it is a react native issue, mentioned here [https://github.com/facebook/react-native/issues/31251](https://github.com/facebook/react-native/issues/31251), and it has not been fixed in react native even though a recent comment says otherwize. But the solution given in the issue thread worked for me.

**Comment by gavrichards** [comment]
I've experienced this, but as you say, it's a known React Native issue.
