### ISSUE TITLE
Is this Library will be still maintained in the futur

### ISSUE THREAD

**Issue by bouaoud** [birkir/react-native-carplay#12]
Hello Team,

I will perhaps start a big project with great automobile entreprise and I want to know what can i do with existing Library of React Native Carplay, and also fi this Library will be still maintained in the futur.

What about Android car Library ? it is planned to be developed ?

Thank you so much

**Comment by birkir** [comment]
Yes, I plan to update this library with the stable iOS CarPlay framework releases. Waiting for iOS 14 for next version.
This library is only for CarPlay not Android Auto.
