### ISSUE TITLE
Disabling com.apple.developer.carplay-maps entitlement

### ISSUE THREAD

**Issue by HarmJan1990** [birkir/react-native-carplay#121]
Hi,

Does anyone know if we can use this package without the maps entitlement?
I build something today and want to try it on device that doesn't use any maps.
Is there a way to remove the maps entitlement need?

**Comment by mawlicious** [comment]
yes you can, the maps entitlement is not there by the library, its completely up to what you put in the Entitlements.plist afaik.

**Comment by gavrichards** [comment]
I believe the only way is to use it with Scenes. See the example project that uses Scenes:
https://github.com/birkir/react-native-carplay/tree/master/example-scenes

**Comment by birkir** [comment]
I added entitlement matrix here:

https://github.com/birkir/react-native-carplay/tree/2.3.0#entitlement-matrix
