### ISSUE TITLE
Https images are not loading in list items

### ISSUE THREAD

**Issue by harrymash2006** [birkir/react-native-carplay#148]
@birkir the https images are not loading in ListItem, any clue?:

I am using this object:

const podcastItems: ListItem[] = [
    { text: 'Podcast 1', detailText: 'Podcast 1 description', image: { uri: 'https://commondatastorage.googleapis.com/codeskulptor-assets/week5-triangle2.png'}},
  ]

**Comment by DanielKuhn** [comment]
The documentation is wrong. I fixed it (and improved remote image loading) in https://github.com/birkir/react-native-carplay/pull/143

**Comment by DanielKuhn** [comment]
@harrymash2006 check the [entitlement matrix](https://github.com/birkir/react-native-carplay#entitlement-matrix): `SearchTemplate` is only allowed in maps apps. You probably have another entitlement registered.

As for react-native-track-player: I outlined the integration of react-native-track-player with react-native-carplay in [this issue](https://github.com/doublesymmetry/react-native-track-player/issues/1533)

I don't have a car with CarPlay either, but you can use the external screen of simulator in Xcode. Once you have requested and received the entitlement from Apple for your developer account you can also use the standalone CarPlay simulator which is part of the "Additional Tools for Xcode 15" available in the [downloads section on developer.apple.com](https://developer.apple.com/download/all/).

Once you want to try your CarPlay app on a real device you can also get an external CarPlay client like the one from [Carpuride](https://carpuride.com/).

**Comment by harrymash2006** [comment]
@DanielKuhn I am able to implement it with trakckplayer now, thanks. 

I have one more question, what if we want to play to some audio in carplay with default seek position and start trackplayer. Right now when I push nowplaying template and start TrackPlayer it plays it on the phone and not on the "NowPlaying"

**Comment by DanielKuhn** [comment]
Sounds like you're at the point where you need to test on real devices. As I mentioned before: The carplay window of the simulator is not reliable concerning NowPlaying.
Try rebooting your Mac and try again - that actually helped in my case sometimes. Otherwise I recommend switching to a real device like Carpuride

**Comment by harrymash2006** [comment]
@DanielKuhn thanks for your great help. I think I will take someone's help with a car having a carplay.

Do you have any idea about android auto support for the same? I see Shopify's react-native-android-auto package but it was updated 2 years ago and also it throws errors when building android app.

**Comment by DanielKuhn** [comment]
@harrymash2006 There's a very promising [PR for Android Auto over at RNTP](https://github.com/doublesymmetry/react-native-track-player/pull/2094) with great work by @lovegaoshi that both my team and [the folks at podverse](https://github.com/podverse/podverse-rn/pull/1959) are planning to use in production soon.

**Comment by birkir** [comment]
Fixed in #143
