### ISSUE TITLE
didPresssMenuItem is not an available event on iOS

### ISSUE THREAD

**Issue by janwiebe-jump** [birkir/react-native-carplay#161]
**Describe the bug**
Error: 
`didPressMenuItem` is not a supporte event type for RNCarPlay

**To Reproduce**
1. Use an iOS device, try to start the example project

**Expected behavior**

**Screenshots/Videos**

**CarPlay (please complete the following information):**
 - Device: iPhone 6S
 - OS version 15.5
 - RNCarPlay version react-native-carplay@2.4.0-beta.2

**Android Auto (please complete the following information):**
 - Device: [e.g. Pixel 8 / emulator]
 - Android Version: [e.g. iOS8.1]
 - RNCarPlay version [e.g. 2.4.0]

**Additional context**

**Comment by uzegonemad** [comment]
I looked through the source and I don't think this method is registered on Android either.

@birkir Did you have a vision in mind with `didPressMenuItem`? It doesn't actually appear to be implemented on Android or iOS.

**Comment by thomas-rx** [comment]
Fixed on #162.
