### ISSUE TITLE
Now playing image buttons are broken

### ISSUE THREAD

**Issue by uzegonemad** [birkir/react-native-carplay#171]
**Describe the bug**
Image buttons on the now playing template were broken in 2f26991

If you [see here](https://github.com/birkir/react-native-carplay/commit/2f269917931b92d57c814a062bf5ca8c7950134b#diff-278243590243e6a35a938c7494fe85ffca3a4a0b572f3f1d29df05678decc101L263-R278) you will notice that the `CPNowPlayingImageButton` is no longer using `initWithImage`.

I have a patch that fixes this and will create a PR.

**To Reproduce**
1. Add a now playing template with an image button
2. No image displays on the button (a blank question mark symbol displays instead)

**Expected behavior**
An image to display.

**CarPlay (please complete the following information):**
 - RNCarPlay version 2.4.0-beta.2

**Comment by limadouglas** [comment]
@uzegonemad look at this: https://github.com/birkir/react-native-carplay/issues/6#issuecomment-799256543

The image must have dimensions of 80x80 pixels and be named <something>@3.png.

exemplo:
![arrow@3x](https://github.com/birkir/react-native-carplay/assets/21013545/9d61e0e0-4148-4bf4-86e3-6c6c123b7d74)

**Comment by syedslegend786** [comment]
> **Describe the bug** Image buttons on the now playing template were broken in [2f26991](https://github.com/birkir/react-native-carplay/commit/2f269917931b92d57c814a062bf5ca8c7950134b)
> 
> If you [see here](https://github.com/birkir/react-native-carplay/commit/2f269917931b92d57c814a062bf5ca8c7950134b#diff-278243590243e6a35a938c7494fe85ffca3a4a0b572f3f1d29df05678decc101L263-R278) you will notice that the `CPNowPlayingImageButton` is no longer using `initWithImage`.
> 
> I have a patch that fixes this and will create a PR.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Add a now playing template with an image button
> 2. No image displays on the button (a blank question mark symbol displays instead)
> 
> **Expected behavior** An image to display.
> 
> **CarPlay (please complete the following information):**
> 
> * RNCarPlay version 2.4.0-beta.2

Hi, I am also working on react native app, to work it with android-auto. If you can share your project implementation repo, it will help alot, because i am facing issues with NowplayingTemplate

**Comment by limadouglas** [comment]
Sorry, I can't because it's a private project. 
If you are having issues, I recommend that you join the React Native Carplay Discord server and ask for help: [https://discord.gg/b235pv6QHM](https://discord.gg/b235pv6QHM).
