### ISSUE TITLE
iOS scenes: Looks like you have configured linking in multiple places

### ISSUE THREAD

**Issue by KestasVenslauskas** [birkir/react-native-carplay#174]
After implementing scenes in iOS I get this error from react-native-navigation.
![Simulator Screenshot - iPhone 15 Pro - 2024-03-07 at 13 34 32](https://github.com/birkir/react-native-carplay/assets/52245569/82dff626-340a-4648-ac9a-809e8cacb0d1)

Maybe some one came with a solution?

**Comment by DanielKuhn** [comment]
See https://github.com/facebook/react-native/issues/37278#issuecomment-1985404980

**Comment by KestasVenslauskas** [comment]
It helped! If anyone still having problems with deep links take a look at this https://github.com/facebook/react-native/issues/35191#issuecomment-1333544005
