### ISSUE TITLE
"Unsupported object" error when pushing/presenting templates (example app)

### ISSUE THREAD

**Issue by bitcrumb** [birkir/react-native-carplay#176]
**Describe the bug**
When running the example app, I get "Unsupported object" errors for voice control (present), map (push) and search (push).
Is this something that used to work and has now changed?
And if I try to present these via `setRootTemplate`, I get the same error.

**To Reproduce**
Run Example app and try opening voice/map/search.

**Expected behavior**
I should be able to present these templates.

**Screenshots/Videos**

![Simulator Screenshot - iPhone 15 Pro - 2024-03-25 at 15 37 32](https://github.com/birkir/react-native-carplay/assets/135126/972ad9ec-8c0e-4e18-adfb-c4c609328e65)
![Simulator Screenshot - iPhone 15 Pro - 2024-03-25 at 15 38 12](https://github.com/birkir/react-native-carplay/assets/135126/b3f63249-9496-4baa-a3cf-ec51bcef2d04)
![Simulator Screenshot - iPhone 15 Pro - 2024-03-25 at 15 38 17](https://github.com/birkir/react-native-carplay/assets/135126/9ea59f17-f2f8-4a08-8aed-184709ba7c2c)

**CarPlay (please complete the following information):**
 - Device: Simulator
 - OS version: iOS 17
 - RNCarPlay version: 2.3.4

**Comment by saikiranm33** [comment]
@bitcrumb how do fixed the above issues ?

**Comment by bitcrumb** [comment]
@saikiranm33 The example project missed some entitlements (which got rid of most of the errors, but not all).

**Comment by KestasVenslauskas** [comment]
having same problem on emulator iOS version 15.4
Is this not enough?
<key>com.apple.developer.carplay-audio</key>
<true />
		
iOS version 17+ works fine.

**Comment by ElangoPrince** [comment]
@bitcrumb Facing same issue while using **searchTemplate**. I have added relevant entitlement in my project. (**com.apple.developer.carplay-fueling**). How to fix that?

**Comment by ElangoPrince** [comment]
> @bitcrumb Facing same issue while using **searchTemplate**. I have added relevant entitlement in my project. (**com.apple.developer.carplay-fueling**). How to fix that? @birkir FYI.
> 
> ```
> Exception 'Unsupported object <CPSearchTemplate: 0x600003fc6700> <identifier: 9E253DD3-3912-4F2C-B5C2-B7FD1CD88709, userInfo: {
>     templateId = "search-1714990663678-3200635217977703";
> }, tabTitle: (null), tabImage: (null), showsTabBadge: 0> passed to pushTemplate:animated:completion:. Allowed classes: {(
>     CPInformationTemplate,
>     CPActionSheetTemplate,
>     CPTabBarTemplate,
>     CPAlertTemplate,
>     CPGridTemplate,
>     CPPointOfInterestTemplate,
>     CPListTemplate
> )}' was thrown while invoking pushTemplate on target RNCarPlay with params (
>     "search-1714990663678-3200635217977703",
>     1
> )
> ```

I'm closing this issue. Since, Map's entitlements is required to use search template.
