### ISSUE TITLE
How to use master branch package.json + yarn?

### ISSUE THREAD

**Issue by KestasVenslauskas** [birkir/react-native-carplay#183]
There is some critical fixes on master branch, but there is no release yet. How to use master branch?
When setting `"react-native-carplay": "https://github.com/birkir/react-native-carplay.git#master",`
I get this error `invalid package version undefined`

**Comment by DanielKuhn** [comment]
Since `react-native-carplay` is a monorepo you need to use the package subdirectoy when bundling from a branch/commit.
I'm using gitpkg: https://gitpkg.vercel.app/about/
I.e.: `"react-native-carplay": "https://gitpkg.now.sh/birkir/react-native-carplay/packages/react-native-carplay?{COMMIT-SHA}",`
