### ISSUE TITLE
Now Playing template for CarPlay audio apps

### ISSUE THREAD

**Issue by martinthedinov** [birkir/react-native-carplay#19]
Hi

Any chance you plan on adding other templates, in particular the Now Playing one for CP audio apps? If not, maybe I can add support for this. Let me know please.

Thanks!

**Comment by birkir** [comment]
I am happy to accept pull requests!

**Comment by martinthedinov** [comment]
> I am happy to accept pull requests!

Great. Working on some audio apps with CarPlay now - will try to work in an addition to this module too soon.

**Comment by birkir** [comment]
I added the Now Playing template, but cannot get it working.

Also cannot get PointOfInterest nor Contact templates working.

https://github.com/birkir/react-native-carplay/blob/master/ios/RNCarPlay.m#L143-L150

**Comment by maendamedia** [comment]
Same problem here. No templates are working, or i do something wrong.
I like to use the nowplaying template too and show the now playing and an image on the background.

I only see: CANNOT CONNECT TO NULL_

What am i doing wrong?

**Comment by urtti** [comment]
Any updates on this? I'd need to add CarPlay audio app to a React Native app. Now Playing screen would be pretty much a must-have. Any good ways to work around it?

**Comment by birkir** [comment]
Sorry, I don’t have that the capacity to work on it for now. But as I said happy to accept PRs.

**Comment by urtti** [comment]
> Sorry, I don’t have the capacity to work on it for now. But as I said happy to accept PRs.

No worries, thanks for the quick response and for creating this repo. It's really helpful!

**Comment by ForrestDWS** [comment]
@birkir Do you know when you might be able to find the time to work on adding now playing functionality?

**Comment by gavrichards** [comment]
Has anyone managed to get Now Playing working?

**Comment by birkir** [comment]
Works in 2.3.0

**Comment by syedslegend786** [comment]
> 2.3.0

![image](https://github.com/birkir/react-native-carplay/assets/74596807/ce251c06-1a7c-473c-b792-778d8dc9a091)

Is that working in that version
