### ISSUE TITLE
React/RCTConvert.h not found in RCTConvert+RNCarplay.h

### ISSUE THREAD

**Issue by princekurt** [birkir/react-native-carplay#2]
Hey there, so I have tried installing this on two different projects, one already in motion, and another from scratch. Both are springing this error when I try to build the iOS app. 
<img width="1670" alt="Screen Shot 2019-04-25 at 2 59 08 PM" src="https://user-images.githubusercontent.com/13986385/56761227-ddfc3b00-676a-11e9-91ea-c04a7be65795.png">

**Comment by birkir** [comment]
Do you use Podfile or react native link?

**Comment by princekurt** [comment]
Hello, after further investigation, it seems our react-native version was pulling from the wrong location, and therefore, it was out of date. Thanks for the speedy response.
