### ISSUE TITLE
does this work with expo?

### ISSUE THREAD

**Issue by nh916** [birkir/react-native-carplay#24]
was wondering if this only works with react native cli or also export. Please let me know

**Comment by birkir** [comment]
This will probably not work with Expo in the near future, it needs entitlements and custom iOS code to work.

**Comment by nh916** [comment]
its still a great start!

I am proud of you!

**Comment by chownation** [comment]
@nh916 can try ejecting and running in Expo Bare workflow with SDK39

**Comment by martinthedinov** [comment]
> @nh916 can try ejecting and running in Expo Bare workflow with SDK39

@nh916 , I am running it with some Expo APIs (like `expo-keep-awake`) in parallel, in bare workflow, as @chownation suggests.
