### ISSUE TITLE
Instructions and issue running Example test2.xcworkspace

### ISSUE THREAD

**Issue by chownation** [birkir/react-native-carplay#25]
Running into an issue running Example app - after setting up by (1) yarn in root dir, (2) yarn in example, (3) yarn build:dev in root dir, (4) pod install in example/ios

Wanted to confirm steps to setup as templates appear to be missing images and getting exception below
 
![Simulator Screen Shot - iPhone 11 - 2020-10-24 at 17 27 36](https://user-images.githubusercontent.com/1755207/97093961-3e00c580-161e-11eb-8e34-49fd064e873c.png)
![Simulator Screen Shot - iPhone 11 - 2020-10-24 at 17 27 33](https://user-images.githubusercontent.com/1755207/97093962-3e00c580-161e-11eb-8c1d-e0f99274394d.png)

```
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSGenericException', reason: 'An error was encountered during a template operation, but no completion block was specified. Error: Error Domain=CarPlayErrorDomain Code=-1 "No templates were available to be popped." UserInfo={NSLocalizedDescription=No templates were available to be popped.}'
```

**Comment by birkir** [comment]
Hit reload on the iOS app once you've opened the CarPlay app.

Another option is to force close the iOS app and then open the CarPlay app.

I think this is happening when iOS app starts without CarPlay connected. I still have to work on the connect/disconnect events.

**Comment by tomdye** [comment]
Following the above instructions and reloading appears to get the example app running however most of the functionality appears to be broken.

**Comment by tomdye** [comment]
Will be improved via: https://github.com/birkir/react-native-carplay/pull/33
