### ISSUE TITLE
Guidance on using POI and Navigation functions

### ISSUE THREAD

**Issue by tomdye** [birkir/react-native-carplay#26]
I'm trying to use the react-native-carplay package to add car play functionality to my navigation app. I'm struggling to get the map to work with panning / POI lists / overlays etc as there is little documentation of these features within your Readme. I have tried looking at your example app but the map and the related map features do not appear to be working here either.

Are you able to offer any guidance on what I may be doing wrong or perhaps fix the example app if that is incorrect?

Cheers.
<img width="615" alt="Screenshot 2020-12-21 at 17 07 26" src="https://user-images.githubusercontent.com/814453/102802732-02307500-43af-11eb-946a-376a4ecf62de.png">
<img width="598" alt="Screenshot 2020-12-21 at 17 07 39" src="https://user-images.githubusercontent.com/814453/102802751-09f01980-43af-11eb-967a-f2a7a8740b43.png">

**Comment by birkir** [comment]
Map is only referring to the map feature of CarPlay.

You have to implement your own map here, I provide a React View where you can render your own “Map”, whatever that is.

If you want something out of the box, please checkout Mapbox, they have an CarPlay feature.

I highly recommend reading the documentation for CarPlay before using this library
https://developer.apple.com/documentation/carplay/

**Comment by tomdye** [comment]
Thanks for your speed response. Within my app I have indeed got a `Map` to render but am now looking to use the POI template / list template / navigation screens etc - none of which appear to be working right now in my app or within the example app you created in this repo.

**Comment by birkir** [comment]
Oh sorry I read the issue incorrectly.

You can take a look at the source to see how I bridged the POI and Navigation features.

I do want to note that I didn’t get the POI to work for me, as there was a bug within iOS 14 at the time.

But for navigation, everything should work correctly, if they don’t, something has broken since I was working on this.

latest iOS update broke many things

**Comment by tomdye** [comment]
Regarding the `POITemplate` specifically, one of the things that stood out from the carplay developer guide was that it is not supported for navigation apps which I found odd.

>The point of interest template can be used by EV charging, parking, and quick food ordering
apps. 

It doesn't appear that navigation is working, did you ever get an example running where you were able to display a POI overlay over the map base / root template or where you were able to start navigation?

**Comment by tomdye** [comment]
Fixed via https://github.com/birkir/react-native-carplay/pull/33
