### ISSUE TITLE
No visible @interface for 'CPManeuver' declares the selector 'setJunctionImage:'

### ISSUE THREAD

**Issue by PHClement** [birkir/react-native-carplay#3]
Hello,

I have an error on build, can you help me please ? 

`No visible @interface for 'CPManeuver' declares the selector 'setJunctionImage:'`

Thank you in advance.

**Comment by birkir** [comment]
Maybe bump up your ios target? Needs to be SDK 12.2+

https://developer.apple.com/documentation/carplay/cpmaneuver/3081779-junctionimage?language=objc
