### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by maendamedia** [birkir/react-native-carplay#30]
Hi all,

I tried one of the demos, but whichever I test, I keep getting the following error (and crash) when building on the simulator:

```
Terminating app due to uncaught exception 'NSGenericException', reason: 'Application does not implement CarPlay template application lifecycle methods in its scene delegate.'
terminating with uncaught exception of type NSException
```

Where to look for this issue? I followed all the installation steps provided by this module.

**Comment by maendamedia** [comment]
Merry Christmas everyone.


Any ideas on this?

The error seems to go away, but all demos show me a black screen on the simulator now :(

**Comment by jm81** [comment]
I'm also getting this, both in the demo and in another app. It seems to be an issue with simulators running ios 14. If I switch to another simulator with ios 13, I still get errors. It seems like I have to clean the build and delete the app from the simulator, and then it works on the next build. I've just been trying out things in an unstructured way so there's a good chance I'm missing factors. If I have a chance to do more structured experimenting, I will update with whatever else I figure out. The discussion of entitlements in https://developer.apple.com/carplay/documentation/CarPlay-App-Programming-Guide.pdf makes me wonder if the entitlements plist needs changes for ios 14, but that's just a guess based on not very close reading.

**Comment by objectiveSee** [comment]
The OP error message indicates that the required delegate methods aren't implemented.

**Comment by tomdye** [comment]
It seems to me that a lot more of this used to work with ios13

**Comment by tomdye** [comment]
If you set the build target to ios14+ in the react native car play pod settings or manually remove all the `#if __IPHONE_OS_VERSION_MIN_REQUIRED >= 140000` code snippets it starts to work a bit better.

**Comment by maendamedia** [comment]
> The OP error message indicates that the required delegate methods aren't implemented.

Correct, but the installation instructions are followed.

A little late response but i still have these issues :(
Not sure how to fix this.

**Comment by maendamedia** [comment]
Any idea how to get it to work anyhow?
I keep getting blank screens, no visible thingies OR i see the message: CANNOT CONNECT TO <appname>

**Comment by tomdye** [comment]
I've fixed a series of connect / disconnect and issues with existing connections in my `improvements` branch along with many other ios14 things. Might be worth taking a look to see if it fixes some of your issues too?
https://github.com/birkir/react-native-carplay/pull/32

**Comment by tomdye** [comment]
@maendamedia @jm81 take a look at https://github.com/birkir/react-native-carplay/pull/33 - this should fix your issues if your using the package for an ios14 build

**Comment by jm81** [comment]
@tomdye @birkir I finally got back to working on the project where I was having issues, and the 2.0.0 release is working great for me. Thank you!
