### ISSUE TITLE
MapTemplate - State Changes

### ISSUE THREAD

**Issue by dave-moser** [birkir/react-native-carplay#31]
When using the MapTemplate, updating a state variable in the containing function component causes the entire Map to reload.  The map does not refresh in-place.  The map fully reloads, returning to a fully zoomed out state and then zooms into the set region.  This happens every time the containing function updates a state variable.

**Comment by tomdye** [comment]
is that because your use-effect is relying on that state variable and thus fully re-running? I had a similar issue but needed to add appropriate native code to handle the updating of the mao

**Comment by dave-moser** [comment]
In one of my useEffects I update a state variable based on receiving values from a data subscription.  It is a different useEffect than the one that calls CarPlay.setRootTemplate() if that matters.  I also have the mobile phone view displaying the map and the value received from the subscription, and updating the state variable does not cause the phone's map to reload.

**Comment by tomdye** [comment]
I had to write a bridge function for my map implementation in native. I've got an improvements branch of this repo on my fork which i'm working on to get some more features implemented for ios14. Not needed to update my map reactively yet as the developer designed it to be interacted with via a API on it's ref.

**Comment by birkir** [comment]
It would be great to see an example reproduction of this bug

**Comment by dave-moser** [comment]
Sure.  I took your example from Maps and added a react-native-maps mapping component.  I then updated your **onShowAlertPress** function to perform a simple state variable increment.  Each time I hit that function it causes the entire map to reload. 

`import React, { useEffect, useState } from 'react';
import { Button, Text, View } from 'react-native';
import { CarPlay, MapTemplate, Trip } from 'react-native-carplay';
import MapView from 'react-native-maps'

function CarMapView() {
  return (
    <View style={{ flex: 1}} >
      <MapView style={{flex: 1}}  showsUserLocation={true} followsUserLocation={true} />
    </View>
  );
}

export function Map({ navigation }) {

  const [navigationSession, setNavigationSession] = useState(null);
  const [mapValue, setMapValue] = useState(0);

  const mapTemplate = new MapTemplate({
    component: CarMapView,
    onAlertActionPressed(e) {
      console.log(e);
    }
  });

  const onShowAlertPress = () => {
    // mapTemplate.presentNavigationAlert({
    //   titleVariants: ['Test 1'],
    //   primaryAction: { title: 'Test 2' },
    //   secondaryAction: { title: 'Test 3'},
    //   duration: 1000,
    // });
    var value = mapValue + 1
    setMapValue(value)
  }

  const onDismissAlertPress = () => {
    mapTemplate.dismissNavigationAlert(true);
  }

  const onShowPanningPress = () => {
    mapTemplate.showPanningInterface(true);
  };

  const onDismissPanningPress = () => {
    mapTemplate.dismissPanningInterface(true);
  };

  const onShowPoiPress =() => {
    return navigation.navigate('POI');
  }

  const onStartNavigation = async () => {

    const trip = new Trip({
      origin: {
        latitude: 64,
        longitude: -21,
      },
      destination: {
        latitude: 64.5,
        longitude: -21.5,
      },
      routeChoices: [{
        additionalInformationVariants: ['a'],
        selectionSummaryVariants: ['b'],
        summaryVariants: ['c'],
      }],
    });

    setNavigationSession(await mapTemplate.startNavigationSession(trip));
  };

  useEffect(() => {
    CarPlay.pushTemplate(mapTemplate, false);
    return () => CarPlay.popToRootTemplate(true);
  }, []);

  return (
    <View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
      <Button title="POI" onPress={onShowPoiPress} />
      <Button title="Show alert" onPress={onShowAlertPress} />
      <Button title="Dismiss alert" onPress={onDismissAlertPress} />
      <View style={{ height: 16 }} />
      <Button title="Show panning" onPress={onShowPanningPress} />
      <Button title="Dismiss panning" onPress={onDismissPanningPress} />
      <View style={{ height: 16 }} />
      {navigationSession ? (
        <>
          <Text>Navigation:</Text>
          <Button title="Pause" onPress={() => navigationSession.pause(1, 'Paused')} />
          <Button title="Cancel" onPress={() => { navigationSession.cancel(); setNavigationSession(null) }} />
          <Button title="Finish" onPress={() => { navigationSession.finish();  setNavigationSession(null); }} />
        </>
      ) : (
        <Button title="Start Navigation" onPress={onStartNavigation} />
      )}
    </View>
  )
}

Map.navigationOptions = {
  headerTitle: 'Map Template',
};
`

**Comment by dave-moser** [comment]
Separately, I was also trying to bind items on a ListTemplate to state variables and the text of the list items would not update when the state variables changed.

**Comment by tomdye** [comment]
Try assigning your map template to a ref and calling `updateConfig` on it if it already exists, then make your useEffect in which you create it depend on any of the state it requires to re-render. Same goes for your `ListTemplate`, there's an updateListItems function you can call.

**Comment by birkir** [comment]
Yeah just use a ref, you are creating a new instance of the template on every render. The example code is showing bad practises, will update.

```
function MapScreen() {

  const mapTemplate = useRef(new MapTemplate({
    component: CarMapView,
    onAlertActionPressed(e) {
      console.log(e);
    }
  }));

  useEffect(() => {
    CarPlay.pushTemplate(mapTemplate.current, false);
  }, []);
  
  return null;
}
 ```

**Comment by HarmJan1990** [comment]
Did you ever fix this @dave-moser?
I'm trying to update the map using updateConfig but it's not updating the component.
I would like to update markers on the map.

**Comment by dave-moser** [comment]
No, @HarmJan1990, I migrated my solution over to native iOS.
