### ISSUE TITLE
Cant Connect to App

### ISSUE THREAD

**Issue by carlos-nunez** [birkir/react-native-carplay#36]
Xcode: 12.4 
IOS Simulator Version: 14.4
M1 Mac

I'm having an issue where the CarPlay app builds but when it tries to connect it says "Cannot connect to `Myappname`"

**Comment by carlos-nunez** [comment]
In App.js

`
  const gridTemplate = new GridTemplate({
    buttons: [],
    title: "Hello, world",
  });

  useEffect(() => {
    function onConnect() {
      console.log("Yolt");

      setCarPlayConnected(true);
    }

    function onDisconnect() {
      setCarPlayConnected(false);
    }

    CarPlay.setRootTemplate(gridTemplate);

    CarPlay.registerOnConnect(onConnect);
    CarPlay.registerOnDisconnect(onDisconnect);

    return () => {
      CarPlay.unregisterOnConnect(onConnect);
      CarPlay.unregisterOnDisconnect(onDisconnect);
    };
  }, []);`


Im getting the error: 
Application does not implement Carplay template application lifecyles.

I've also tried setting the root template the same way the example does.

**Comment by birkir** [comment]
Did you follow the setup guide for XCode?

**Comment by carlos-nunez** [comment]
> Did you follow the setup guide for XCode?

I think so? I created an entitlements file I didnt find any other instructions besides that

**Comment by brightsider** [comment]
Use UIApplicationSceneManifest like in apple example
