### ISSUE TITLE
[NOT-A-BUG] Anyone using this in production ?

### ISSUE THREAD

**Issue by e-nouri** [birkir/react-native-carplay#37]
I am wondering if anyone is using this in production ? If yes is it on iOS 14 or 13 ?
Thank you for putting this repo together, I appreciate the docs as well, they are pretty helpful even on their own.

**Comment by princekurt** [comment]
We are building for production. We converted the code for 14, and pushed it up here. I believe it's now apart of the repo. So it does work quite well with iOS 14!

**Comment by tomdye** [comment]
Yup

**Comment by sopranolinist** [comment]
@princekurt @tomdye are either of you using the NowPlaying template in your production apps?

**Comment by tomdye** [comment]
afraid not

**Comment by e-nouri** [comment]
Awesome 🤩 thank you guys 👍
