### ISSUE TITLE
Now playing

### ISSUE THREAD

**Issue by maendamedia** [birkir/react-native-carplay#43]
Hi,

is there any progress on the now playing template?

i like to integrate it with react native track player to show now playing and cover art, but not sure how to do this.

thanks

**Comment by maendamedia** [comment]
Any ideas on this?

**Comment by birkir** [comment]
Looks like we need to implement the CPNowPlayingTemplateObserver for button events.

Also the types of available buttons, which are
- CPNowPlayingImageButton
- CPNowPlayingAddToLibraryButton
- CPNowPlayingMoreButton
- CPNowPlayingPlaybackRateButton
- CPNowPlayingRepeatButton
- CPNowPlayingShuffleButton

The template also requires an “audio” entitlement.

Also you would need a package to manage the MPNowPlaying with an external library like https://github.com/tanguyantoine/react-native-music-control

**Comment by maendamedia** [comment]
Hi Birkir, 

Ok, that needs to be implemented in the library you mean?
An audio entitlement is already present and rnmc also :)

Thanks for this good work!

**Comment by maendamedia** [comment]
> Hi Birkir,
> 
> Ok, that needs to be implemented in the library you mean?
> An audio entitlement is already present and rnmc also :)
> 
> Thanks for this good work!

Can you let me know?

**Comment by birkir** [comment]
Needs to be implemented in the library

**Comment by maendamedia** [comment]
> Needs to be implemented in the library

Ok, thanks. That would be very great, as we have  a lot of requests for it :)

**Comment by ForrestDWS** [comment]
I'm trying to implement the NowPlayingTemplate as well. Where does this library catch me trying to use NowPlayingTemplate in pushTemplate()? Thank you!
![Simulator Screen Shot - iPhone 11 - 2021-06-24 at 16 58 20](https://user-images.githubusercontent.com/75861606/123346623-94a40380-d50d-11eb-9ba0-1ac46d106bd8.png)

**Comment by ForrestDWS** [comment]
> I'm trying to implement the NowPlayingTemplate as well. Where does this library catch me trying to use NowPlayingTemplate in pushTemplate()? Thank you!
> ![Simulator Screen Shot - iPhone 11 - 2021-06-24 at 16 58 20](https://user-images.githubusercontent.com/75861606/123346623-94a40380-d50d-11eb-9ba0-1ac46d106bd8.png)

Ah, nm, i had the wrong entitlement set up :)

**Comment by maendamedia** [comment]
> > I'm trying to implement the NowPlayingTemplate as well. Where does this library catch me trying to use NowPlayingTemplate in pushTemplate()? Thank you!
> > ![Simulator Screen Shot - iPhone 11 - 2021-06-24 at 16 58 20](https://user-images.githubusercontent.com/75861606/123346623-94a40380-d50d-11eb-9ba0-1ac46d106bd8.png)
> 
> Ah, nm, i had the wrong entitlement set up :)

Does this mean you got it working?
If so: may i ask how you’ve done it? ☺️

**Comment by ForrestDWS** [comment]
@maendamedia I could not. I took a break from this. But I just noticed this PR that seems to enable it: https://github.com/birkir/react-native-carplay/pull/48

**Comment by ForrestDWS** [comment]
> > I'm trying to implement the NowPlayingTemplate as well. Where does this library catch me trying to use NowPlayingTemplate in pushTemplate()? Thank you!
> > ![Simulator Screen Shot - iPhone 11 - 2021-06-24 at 16 58 20](https://user-images.githubusercontent.com/75861606/123346623-94a40380-d50d-11eb-9ba0-1ac46d106bd8.png)
> 
> Ah, nm, i had the wrong entitlement set up :)

Actually, I'm not sure about whether my entitlements are wrong. What should I have set in my entitlements.plist file? Here are my current ones 
`	<key>com.apple.developer.carplay-parking</key>
	<true/>
	<key>com.apple.developer.carplay-audio</key>
	<true/>
	<key>com.apple.developer.carplay-communication</key>
	<true/>
	<key>com.apple.developer.carplay-charging</key>
	<true/>
	<key>com.apple.developer.carplay-maps</key>
	<true/>`

**Comment by gavrichards** [comment]
I would love to use this library but require a now playing screen as it's for a radio playing app.

**Comment by rajpootathar** [comment]
Any timeline for this now playing feature?

**Comment by gavrichards** [comment]
Is there any update on this?

Weirdly, this release actually mentions it now includes a Now Playing Template:
https://github.com/birkir/react-native-carplay/releases/tag/0.3.0

But at the bottom of the README, there's a section titled "Not working / In progress", and it includes Now Playing Template, and there's no example given.

**Comment by birkir** [comment]
https://github.com/birkir/react-native-carplay/blob/0.3.0/ios/RNCarPlay.m#L143-L150

Still missing three configuration parameters

**Comment by gavrichards** [comment]
Still getting this error screen:
![simulator_screenshot_AD31844C-F96F-43D9-A1E3-84CB4BB624BD](https://user-images.githubusercontent.com/432315/185924161-3b783ad6-a943-406a-a489-b8a9f5f0a163.png)

Calling this after registering the callbacks:
```
CarPlay.enableNowPlaying(true);
```

and then adding the now playing screen in a temporary fashion like this:
```
  const gridTemplate = new GridTemplate({
    title: 'Hello, World',
    buttons: [],
  });
  CarPlay.setRootTemplate(gridTemplate);

  setTimeout(() => {
    const nowPlaying = new NowPlayingTemplate({
      albumArtistButton: false,
      upNextButton: false,
      upNextTitle: '',
    });
    CarPlay.pushTemplate(nowPlaying, false);
  }, 2000);
```

Has anybody got any suggestions?

**Comment by Summurai** [comment]
Any updates or time estimation on that?

**Comment by Czarczynski** [comment]
@birkir Is there any chance to get Now Playing this year?

**Comment by dani-cabal** [comment]
Hi! Has anyone been able to get NowPlaying template to work? I can't find any instructions anywhere to show the template, as it's not supposed to be pushed or presented like any other.

**Comment by birkir** [comment]
https://github.com/birkir/react-native-carplay/blob/master/example/src/screens/NowPlaying.tsx

Please reopen if there is still an issue with Now Playing 🙂

**Comment by DanielKuhn** [comment]
> Hi! Has anyone been able to get NowPlaying template to work? I can't find any instructions anywhere to show the template, as it's not supposed to be pushed or presented like any other.

I got it to work by adding a button for it in `apps/example/src/screens/Menu.tsx` and only setting the entitlement to `com.apple.developer.carplay-audio`

The entitlements seem to be mutually exclusive... See the [entitlement-matrix](https://github.com/birkir/react-native-carplay#entitlement-matrix): Now playing is only allowed for audio apps. When combining with other entitlements, these seem to block the audio entitlement/NowPlaying-screen.
Likewise, for the audio entitlement screens like Map, Search and Info are blocked.

You need to set the entitlements according to the matrix depending on which screens you want to test.

**Comment by jakob-fankhauser** [comment]
@DanielKuhn 

Did you also manage to display the artwork image from RNTP in CarPlay?

**Comment by DanielKuhn** [comment]
> @DanielKuhn
> 
> Did you also manage to display the artwork image from RNTP in CarPlay?

As mentioned above, this is handled by the apple ecosystem itself: If a track with artwork is running in RNTP, then the artwork is visible throughout the whole ecosystem:
- iOS/iPadOS control center
- iOS/iPadOS lock screen
- watchOS "Now Playing" app
- CarPlay Now Playing template

The Simulator on macOS (External Displays > CarPlay) sometimes is unreliable with showing the artwork, but I haven't had any problems with a real CarPlay device.

**Comment by DanielKuhn** [comment]
@jakob-fankhauser note also that the CarPlay-window of the Simulator app (External Displays > CarPlay) represents a very small CarPlay screen where the artwork is used only as a blurred background in the NowPlaying screen. On larger CarPlay screens the artwork is positioned to the right of the timeline and metadata.

**Comment by DanielKuhn** [comment]
@elieT27 In development you can simply set the entitlement yourself.
An "actual" entitlement from apple is only needed for releasing via appstore

**Comment by syedslegend786** [comment]
> Hi,
> 
> is there any progress on the now playing template?
> 
> i like to integrate it with react native track player to show now playing and cover art, but not sure how to do this.
> 
> thanks

Hi, do you have any example project running with , react-native-track-payer, react-native-car-player. I am gettings error when i push noewPlayingTemplate

**Comment by syedslegend786** [comment]
> @DanielKuhn To clear this up without an actual entitlement I cannot test implementing NowPlaying template on my app using RNTP ?

Did you able to use NowPlayingTemplate with RNTP?
if yes could you please share the repo of yours, because mine is not working.
its giving template not found

**Comment by Ali-ch88** [comment]
@DanielKuhn I need some guidelines regarding NowPlayingTemplate with RNTP.
Currently, we're working on the React Native application in which we have implemented the React Native track player, now our goal is to connect our app with the Android auto and We're using NowPlayingTemplate for this purpose but having this issue, So need to confirmation that NowPlaying Template is working properly with RNTP or not?
![ss34](https://github.com/birkir/react-native-carplay/assets/61835503/0c9f568c-5602-4f8b-8363-ec507d380e95)

**Comment by DanielKuhn** [comment]
> Hi all, I'm currently working on integrating Android Auto and CarPlay with our react native app, which uses react-native-track-player for audio playback:
> 
> For **CarPlay**, the [current master of react-native-carplay by @birkir](https://github.com/birkir/react-native-carplay) features a NowPlaying-template which integrates smoothly with RNTP, since RNTP syncs with the native iOS audio player and the NowPlaying view is accessible throughout the whole Apple ecosystem (iOS/iPadOS, watchOS, and of course CarPlay), so displaying the currently running track is as simple as playing it in RNTP and then pushing the NowPlaying template onto the CarPlay view stack.
> 
> For **Android Auto** there's active development in [this RNTP-PR by @lovegaoshi ](https://github.com/doublesymmetry/react-native-track-player/pull/2094) which also features a NowPlaying-view for Android Auto.

Please see above ⬆️
I cannot share code because it is a private project, but as I stated above we're using `react-native-carplay` for iOS and @lovegaoshi 's branch of RNTP for Android in production.
I don't know the current state of the Android implementation (including NowPlaying) of `react-native-carplay`.
