### ISSUE TITLE
CarPlay crashes the app on launch

### ISSUE THREAD

**Issue by michalis-ligopsychakis** [birkir/react-native-carplay#47]
Hello everyone.. I am new in carplay and I have this issue...

I made the setup as this library suggests and I run my App in many different ios simulators (iPhone 11, 12 in iOS 14.4, 14.2, 13.0).. I also tried to run the example that the library provides..

The problem is that when I open carplay as an external window, I can see the icon of my app but when I click on it, the app close on iOS and carplay simulator without any errors..
Also I saw that CarPlay.connected is false even If I can see the app's icon on carplay simulator..

Can anyone help..?
Any ideas are welcome...

**Comment by tomdye** [comment]
What version of iOS are you using in your simulator please? The latest version of this package will only support 14. 
Did you try adding an on connect callback? https://github.com/birkir/react-native-carplay#connect--disconnect

**Comment by michalis-ligopsychakis** [comment]
Thanks for the response @tomdye...

I have simulators with iOS version 14.4, 14.2 and 13.0...
Now I am downloading iOS 14.0 to see if there is any difference..

I included these (connect-disconnect) methods on my code but they never get called...
Do I have to expect the app on carplay to open automatically when app opens on ios simulator..?

**Comment by tomdye** [comment]
iOS 14.x should be fine.
Yes, you will need to open the app on the phone and on carplay.

**Comment by michalis-ligopsychakis** [comment]
ok thanks...
The weirdest is that I have the same problem when running the example of the library..
I am sending a demonstration of the crash...

https://user-images.githubusercontent.com/78353007/123261366-5bfd2d80-d4ff-11eb-8798-231dbcd8d4c7.mov

**Comment by tomdye** [comment]
Are you sure that you have the latest version on the `react-native-carplay` package installed?

**Comment by michalis-ligopsychakis** [comment]
Yes I have the "react-native-carplay": "^2.0.0" on package.json of example folder

**Comment by nixolas1** [comment]
I also have this issue. react-native-carplay 2.0.0, react native 0.64.2 (also had this at 0.64.0).

**Comment by michalis-ligopsychakis** [comment]
I have react-native version "^0.63.3"...
At first I thought it was a problem of simulator that I was used "iPhone 11 (iOS 14.4)" but no...
I also tried to run a carplay example in Swift from this link ( https://github.com/KKBOX/KKCarPlayManager ) and it worked fine...

**Comment by michalis-ligopsychakis** [comment]
Here is the error that I just took from xCode running the example of the library...

`Crashed Thread:        0  Dispatch queue: com.apple.main-thread
Exception Type:        EXC_CRASH (SIGKILL)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
Termination Reason:    **_Namespace FRONTBOARD, Code 0x8badf00d_**
Application Specific Information:
CoreSimulator 732.18.6 - Device: iPhone 11 (6069E264-B8E8-4A3D-8772-F6E72EC4CE21) - Runtime: iOS 14.4 (18D46) - DeviceType: iPhone 11
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00000001bd7bc284 mach_msg_trap + 8
1   libsystem_kernel.dylib        	0x00000001bd7bc628 mach_msg + 72
2   com.apple.CoreFoundation      	0x0000000180364a10 __CFRunLoopServiceMachPort + 376
3   com.apple.CoreFoundation      	0x000000018035ef1c __CFRunLoopRun + 1152
4   com.apple.CoreFoundation      	0x000000018035e58c CFRunLoopRunSpecific + 572
5   com.apple.GraphicsServices    	0x000000018b9c2740 GSEventRunModal + 160
6   com.apple.UIKitCore           	0x00000001843ccbf0 -[UIApplication _run] + 964
7   com.apple.UIKitCore           	0x00000001843d19d0 UIApplicationMain + 112
8   com.apple.Maps                	0x00000001025dabe8 main + 72
9   libdyld.dylib                 	0x0000000180223cbc start + 4`

**Comment by birkir** [comment]
Can you paste the device logs rather than the stack

**Comment by michalis-ligopsychakis** [comment]
@birkir thanks for the response..
I have no error from the device logs... It just terminates simulator and carplay immediately...

**Comment by michalis-ligopsychakis** [comment]
ok I am getting some error logs on system.log:

Jun 29 14:13:52 xiaomirepeater_v3 test2[16616]: assertion failed: 20B29 18D46: libxpc.dylib + 35842 [26B6416F-496E-32F6-AC9D-FFCD86331B43]: 0x87

Jun 29 14:13:52 xiaomirepeater_v3 com.apple.CoreSimulator.SimDevice.6069E264-B8E8-4A3D-8772-F6E72EC4CE21[13795] (UIKitApplication:org.reactjs.native.example.test2[442a][rb-legacy][16616]): Service exited due to SIGABRT

**Comment by birkir** [comment]
https://github.com/facebook/react-native/issues/20318#issuecomment-415349996 ?

**Comment by michalis-ligopsychakis** [comment]
thanks for the link @birkir... but I still have the issue..
However, I am just trying to run the example that this library provides so it's weird cause I am following the instructions..
Is there someone that can run it and open carplay successfully..?

**Comment by ForrestDWS** [comment]
Yeah, i was able to run the example project successfully @michalis-ligopsychakis and open carplay successfully.

**Comment by michalis-ligopsychakis** [comment]
Thank you @ForrestDWS...
I am using iPhone11 on iOS 14.4...

**Comment by michalis-ligopsychakis** [comment]
@ForrestDWS  also what version of xCode do you use..?

**Comment by michalis-ligopsychakis** [comment]
I updated xCode to 12.5.1 and now it works..
I am not sure if that was the problem because until now I was starting the simulator from terminal and not from xCode (and still not working with this way)...

**Comment by michalis-ligopsychakis** [comment]
Closing issue because I finally run the example on simulator iPhone 11 iOS 14.5 (starting it from xCode and not from terminal)

**Comment by birkir** [comment]
What Xcode version did you have before, just for reference?

**Comment by michalis-ligopsychakis** [comment]
I had Xcode 12.4.0

**Comment by michalis-ligopsychakis** [comment]
Today I run the example and on my previous Xcode version (12.4) and it's fine...
As I understand the problem is when starting the simulator from terminal and not from Xcode ...
