### ISSUE TITLE
Application does not implement CarPlay template application lifecycle methods in its scene delegate

### ISSUE THREAD

**Issue by michalis-ligopsychakis** [birkir/react-native-carplay#49]
Hello everyone..

I am trying to open carplay in my app and I am taking this error: 
Terminating app due to uncaught exception 'NSGenericException', reason: 'Application does not implement CarPlay template application lifecycle methods in its scene delegate.' ..

This error shows on 'main.m ' file..

Can anyone help to that..?
Thanks in advance!!

**Comment by michalis-ligopsychakis** [comment]
I found that this error occurs because of two things:
- config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64" , this line on podfile and
- on Build Settings in Xcode: Excluded Architectures -> Any iOS Simulator SDK - arm64

The problem is that I use some Libraries that needs these to be set...
Also I use MacBook with M1, is this a reason for these problems..?

**Comment by michalis-ligopsychakis** [comment]
Finally I solved the problem...
It was that I used MacBook M1 and I had to set Excluded Architectures to arm64...

On iMac Catalina works fine..

Unfortunately there was no support for this issue.. 
Anyway I think that this will help a lot anyone has the same issue as there is not much info on the internet about CarPlay..

Happy Coding!!

**Comment by naftalibeder** [comment]
@michalis-ligopsychakis can you explain this line?

> It was that I used MacBook M1 and I had to set Excluded Architectures to arm64

It looks like you had already been doing that several days earlier in the `Podfile`, and it wasn't working (?):

```
config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
```

If you could explain what you ended up doing to make it work, as in your post on July 13, that would be very helpful. Thanks!
