### ISSUE TITLE
Error during convertion from JSON value to UIColor

### ISSUE THREAD

**Issue by marcs7** [birkir/react-native-carplay#5]
I'm having an issue duiring the execution of the MapTemplate example:

JSON value '#f0f8ff' of type NSString cannot be converted to a UIColor. Did you forget to call processColor() on the JS side?

+[RCTConvert UIColor:]
    RCTConvert.m:532
-[RNCarPlay applyConfigForMapTemplate:templateId:config:]
-[RNCarPlay createTemplate:config:]
__invoking___
-[NSInvocation invoke]
-[NSInvocation invokeWithTarget:]
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
start

this issue is caused by the parameter ` guidanceBackgroundColor: '#f0f8ff'`
How i can solve this error?
This modue is important for my personal project and it requires to use react native
Thanks for help

**Comment by birkir** [comment]
Is this still an issue? Please re-open if it is.
