### ISSUE TITLE
Is the carplay-map a must-have entitlement?

### ISSUE THREAD

**Issue by coda1997** [birkir/react-native-carplay#50]
I have a project with carplay-messaging and carplay-calling. so can I use this project integrated in my app without carplay-map entitlement?

I run the example code test2 and its pretty cool. If I delete the carplay-map entitlement and delete all component associatied with navigation, it crashed when launching on CarPlay.

**Comment by michalis-ligopsychakis** [comment]
I can see that too...
If I delete the carplay-map entitlement, the app and carplay crashed with error: "Application does not implement CarPlay template application lifecycle methods in its scene delegate."

**Comment by coda1997** [comment]
I am pretty sure this project must need carplay-maps entitlement. The code shows that it draw ui on the map layer. It may be impossible to use this project on an existing project which may not have the entitlement. It's pretty sad :(
