### ISSUE TITLE
Question about Point Of Interest template

### ISSUE THREAD

**Issue by michalis-ligopsychakis** [birkir/react-native-carplay#51]
Hello everyone!!

I want to use the Point Of Interest template 🤓.
I know that it's on TODOS of this package, however as I am searching the library I can see all the necessary code for this to play, based on documentation ( https://developer.apple.com/documentation/carplay/cppointofinteresttemplate )...

So when I am trying to use this template, app crashes with "Exception 'Unsupported object <CPPointOfInterestTemplate"...

Well can anyone help to find what is missing in order to use Point Of Interest template...? 🙏🏼

* I am willing to do some work in order for this to play (and of course share it), but I need some instructions about how to move on...
I believe there are others that need this feature too so any help is welcome 🤗 ...

**Comment by vvusts** [comment]
@michalis-ligopsychakis Hi did you find solution to avoid crash and use it?

**Comment by michalis-ligopsychakis** [comment]
No, this package cannot perform PointOfInterestTemplate yet based on the way it's built..
For this template needs different Scenes to run on carplay and iPhone..

Check this link: https://adapptor.com.au/blog/enhance-existing-apps-with-carplay
