### ISSUE TITLE
Get it to run on existing project

### ISSUE THREAD

**Issue by nixolas1** [birkir/react-native-carplay#53]
Hi, I've been trying to get carplay to work on an existing react native project, but it just crashes when i start the carplay app. ( same error as here https://github.com/birkir/react-native-carplay/issues/49 ) 

I tried creating a completely new RN project and using the example screens, but that crashes.
When using the example project and the existing ios workspace file it works fine.

Not sure what the difference in a newly created RN project and the example project is, as the Appdelegate.m looks identical, and both are set to deployment target 14.1. Is there anything I am forgetting to do to get it to work?

Im on a normal macbook pro, Big Sur, and Xcode 12.5.1

**Comment by nixolas1** [comment]
I figured out what the problem was. I was missing most of the entitlements that were defined in test2.entitlements.
I only had carplay-charging. I guess I have to request ALL entitlements from apple to be able to deploy?

**Comment by nixolas1** [comment]
It seems there are big differences between the Map version of CarPlay and the EV-Charging version. Not only the entitlement, but the whole Appdelegate.m implementation needs to use TemplateSceneDelegate and WindowSceneDelegate to work.

Maybe add a note in the readme @birkir, for future EV-Charging users, that the implementation may vary from the suggested one in the readme :)

**Comment by tomdye** [comment]
It could well be a limitation of the CarPlay simulator then.
