### ISSUE TITLE
POI example crash the app with error: Unsupported object <CPPointOfInterestTemplate:....

### ISSUE THREAD

**Issue by vvusts** [birkir/react-native-carplay#57]
Hi, 

I am trying to use POI template same as in examples but app crash:
```
import {
    CarPlay, PointOfInterestTemplate
} from 'react-native-carplay';

const template = new PointOfInterestTemplate({
            title: 'Example',
            items: [
              {
                id: 'test',
                location: { latitude: 64.011, longitude: -21.66 },
                title: 'Testing',
                subtitle: 'foobar',
              },
            ],
          });
CarPlay.setRootTemplate(template, false);
```

But error that I get is:
![Screenshot 2021-08-20 at 16 11 34](https://user-images.githubusercontent.com/25580183/130246514-b67a4aee-420a-4662-9158-5df7a2094ef9.png)

If this is not possible I tried something else:
<img width="853" alt="Screenshot 2021-08-20 at 16 34 29" src="https://user-images.githubusercontent.com/25580183/130249972-3b63e2b9-3830-4cc6-b07a-0fe7085a98de.png">

```
CarMapView() {
        return (
          <View style={{ flex: 1}} >
            <MapView 
                style={{flex: 1}} 
                provider={PROVIDER_GOOGLE} 
                showsUserLocation={true} 
                followsUserLocation={true}>
                <View style={{backgroundColor: '#f00', padding: 30, marginLeft: 50}}>
                    <TouchableOpacity style={{backgroundColor: '#0ff'}} onPress={() => {CarPlay.pushTemplate(someOtherTemplate);}}>
                        <Text>ITEM A</Text>
                    </TouchableOpacity>
                </View>
            </MapView>
          </View>
        );
      }

const mapTemplate = new MapTemplate({
            component: this.CarMapView
          });
          
CarPlay.setRootTemplate(mapTemplate, false);
```

but this doesn't catch touch event on button over map. Any idea?

**Comment by princekurt** [comment]
Regrettably this hasn't been implemented yet. In the code you can see. 

```
# pragma PointOfInterest
-(void)pointOfInterestTemplate:(CPPointOfInterestTemplate *)pointOfInterestTemplate didChangeMapRegion:(MKCoordinateRegion)region {
    // noop
}
```

**Comment by birkir** [comment]
Supported in 2.3.0

**Comment by Technickster** [comment]
issue is still there in 2.3.0, The method is in there, but the error still remains. The supported events needed "didChangeMapRegion" at the top of the class, but something else is going on that does not allow you to push the POI template to the screen. 

The CPPointOfInterestTemplate is not in the list of Allowed classes . Tried present as well and it is also not supported, is there another way to push this template onto the stack?

**Comment by birkir** [comment]
Yeah we need a `MKCoordinateRegion` to json converter so we can support the event.

The original issue is resolved however, please create a new issue for missing events (or PR)

**Comment by ElangoPrince** [comment]
@vvusts Are you able use **PointOfInterestTemplate** now? Still I'm facing same issue. App getting crash (Closed unfortunately). Can you someone help me how to use this template? 

Adding code sample below: 
```
const template = new PointOfInterestTemplate({
            title: 'Example',
            items: [
                {
                    id: 'test',
                    location: { latitude: 64.011, longitude: -21.66 },
                    title: 'Testing',
                    subtitle: 'foobar',
                },
            ],
        });
        CarPlay.pushTemplate(template, false);
```

**Comment by saikiranm33** [comment]
@birkir  Still facing the same issue , any fix

**Comment by saikiranm33** [comment]
@vvusts  hey are u able to get the POI work ?
