### ISSUE TITLE
Should we create a discord channel for react-native-carplay community discussions?

### ISSUE THREAD

**Issue by tomdye** [birkir/react-native-carplay#60]
@birkir this library appears to be gaining more users. Do you think it would be worthwhile us creating a discord channel? I am happy to do so. It would also help to give collaborators a way to discuss further / plan releases etc.

**Comment by birkir** [comment]
Yes, thats a great idea. Go ahead and create one!

**Comment by tomdye** [comment]
Done, please use the link here to join: https://discord.gg/b235pv6QHM

**Comment by tomdye** [comment]
@birkir discord created as per link above ^^
