### ISSUE TITLE
License MIT or "all rights reserved"

### ISSUE THREAD

**Issue by 3plusalpha** [birkir/react-native-carplay#65]
What is the actual type of license of this project?
I could find MIT in `package.json`, but in files I see `Copyright © 2019 SOLID Mobile. All rights reserved.`.

So is this usable OpenSource from a legal standpoint or not?

**Comment by tomdye** [comment]
As far as I am aware, it is MIT. I will raise a PR to remove those copyright notices and will leave it up to the original author to accept / approve it

**Comment by birkir** [comment]
Its MIT, Xcode adds these copyright notices by default and I forgot to remove them. Thanks @tomdye 

Closed by #66
