### ISSUE TITLE
Map panning buttons not working

### ISSUE THREAD

**Issue by jqn** [birkir/react-native-carplay#69]
Hi! first of all thanks for this library. I'm trying to implement a map and would like to have the user pan or zoom in/out. I'm able to render the map and everything seems to work, except for the buttons. Here is a screenshot of the apple example app that has the same feature, unfortunately, there is no objective c example. Any advice on this, should the buttons work and I'm doing something wrong or they are not finished and need to be finished.  Is there somewhere to find an example of how to fix them, etc, thanks in advance.

<img width="859" alt="Screen Shot 2021-10-26 at 6 30 27 PM" src="https://user-images.githubusercontent.com/9710893/138923997-6a8ee6a4-6539-45b2-bad6-b63e8aa9b368.png">

**Comment by jqn** [comment]
They do not seem to autocomplete for me but it might have to do with my local environment.

**Comment by jqn** [comment]
@tomdye this is what I came up with so far. I also found a way to add extra buttons to the map template.

```
const mapTemplate = useRef(
  new MapTemplate({
    component: MapView,
    onAlertActionPressed(e) {
      console.log(e)
    },
    onMapButtonPressed: ({ id }) => {
      console.log('id', id)
    },
    mapButtons: [
      // { id: 'markerImage', image: zoomOutIcon, titleVariants: ['marker'] },
      { id: 'zoomIn', image: zoomInIcon, titleVariants: ['+'] },
      { id: 'zoomOut', image: zoomOutIcon, titleVariants: ['-'] },
    ],
  }),
)
```
<img width="698" alt="Screen Shot 2021-11-06 at 9 31 37 AM" src="https://user-images.githubusercontent.com/9710893/140603453-16b93f50-603e-4c3d-845c-970aee41dd79.png">

**Comment by tomdye** [comment]
yup, that looks correct to me. Which map view are you using? Feel free to raise a more complete example as a PR to the repo to help others. Thanks

**Comment by jqn** [comment]
@tomdye I'm using react-native-mapbox-gl, thanks for all your help. I was wondering how would I interact with the map template component, in my case the MapView. I would like to set the zoom on the map when the zoom buttons are pressed.

**Comment by tomdye** [comment]
you do that within the JS code, when the template triggers the onMapButton (i forget the name) event, either set some state which the map can react to or use a ref to call a function on the map.

**Comment by jqn** [comment]
@tomdye I have been trying to create a ref to the map template component but it doesn't seem to be working. I'm following the example code. Would you kindly give me a hint on how to do this? I'll sincerely appreciate it. 
```
const mapViewRef = useRef(null)

useEffect(()=> {
    const mapConfig: MapTemplateConfig = {
      component: () => <MapView ref={mapViewRef}/>,
      onAlertActionPressed(e) {
        console.log(e);
      },
      onStartedTrip() {
        onStartNavigation();
      },
      onPanWithDirection(e) {
        onMapPanWithDirection(e);
      },
    };

```
