### ISSUE TITLE
Style options to change UI colors, center elements, etc.

### ISSUE THREAD

**Issue by jqn** [birkir/react-native-carplay#70]
So far I started understanding how this library works and even though I tried to figure out how to check the color of the Grid template title background color, like in the image I can't seem to be able to figure it out. I can try and make the change in the native code if this doesn't work at the moment. Please look at the attached screenshot. I would like to either make the background transparent or at least change the blue color on the title to a different color.
<img width="643" alt="Screen Shot 2021-11-06 at 9 34 16 AM" src="https://user-images.githubusercontent.com/9710893/140603478-b6a5ef0f-baec-4fea-8e03-e36ddd22f61e.png">

**Comment by tomdye** [comment]
that blue colour is the focused colour as it's the only grid item and it's currently focused. It's an OS level theme so not something you can change or have any control over.

**Comment by jqn** [comment]
Thanks a lot, @tomdye. Best.
