### ISSUE TITLE
How to use react-native-carplay sending my destination when I click the button on my React Native app.

### ISSUE THREAD

**Issue by leonidlewis** [birkir/react-native-carplay#74]
I am building the tracking app that contains Map.
When I click the "send location" button on my app( This works on my phone), I want to send the selected address from my phone to Carplay.  Is it possible and which API Can I call on my app?

**Comment by birkir** [comment]
Yes, It's up to you which Map library you will use, and the API to call depends on that.
Feel free to ask on StackOverflow.
