### ISSUE TITLE
SceneDelegate

### ISSUE THREAD

**Issue by birkir** [birkir/react-native-carplay#82]
The previous `CPApplicationDelegate` has been deprecated for the new `CPTemplateApplicationSceneDelegate`.

`CPApplicationDelegate` only works for for iOS and iPadOS 12.0 - 13.0 while the new `CPTemplateApplicationSceneDelegate` implementation is supported for iOS and iPadOS 13.0+ onwards.

I have a working version of the library using the multi scene delegate and will be releasing it soon, but for future releases we will be speaking in terms of Scene delegates and mark previous implementation as legacy.

- Version 2.2 of the library will still support legacy implementation with deployment target to `12`
- Version 3.x we will raise deployment target to `13`, and additionally support Android Auto.

**Comment by tomdye** [comment]
Nice one @birkir , this will please a lot of people who have been struggling with using non map templates due to the delegate causing problems. I think it would be great too though if we could work to get the templates to work reactively rather than via useEffect etc but as this is a breaking change it would also need to be a major release.

**Comment by birkir** [comment]
https://github.com/birkir/react-native-carplay/pull/85

**Comment by gavrichards** [comment]
@birkir is there any news on this? :)

**Comment by gavrichards** [comment]
@birkir do you know when there will be further development with this? We're very keen to use it. Thanks!

**Comment by gavrichards** [comment]
Would you consider enabling the "Sponsor" button, so we could pay towards development? It's extremely important to us. Thanks.

**Comment by pianoman80** [comment]
Hey @birkir Thanks for all your work on this. We would love to see this development continue, it is a very valuable asset for us. Would you consider some way for us to sponsor you to build this out?
