### ISSUE TITLE
Initialization constraint - start the app from car

### ISSUE THREAD

**Issue by vladamx** [birkir/react-native-carplay#96]
When i start carplay app from a car screen i get the black screen because i haven't started the app on the phone first. If i start the app on the phone first and then in the car - everything works fine.
From the architecture standpoint it makes sense since data and controler logic is on JS side.

But for me this is a deal breaker for mixing RN and Carplay.

Is there any workaround this?
Do i get this right? @birkir

**Comment by ouabing** [comment]
Just encounter the same problem. I found if you initialize the RN bridge and rootView in `didFinishLaunchingWithOptions`, the top level JS code will execute. If your CarPlay app does not heavily depend on the JS logics inside your RN views, you can try initialize the CarPlay app in the top level.

**Comment by vladamx** [comment]
Unfortunately, I need to use scenes api for initialization

<img width="924" alt="image" src="https://user-images.githubusercontent.com/11381171/172180952-c96230d1-0ca5-4e69-97b5-ccca7ada3e78.png">

**Comment by ouabing** [comment]
I'm also using scenes. Do you initialize your `rctRootView` in AppDelegate? If so I believe your top level JS code will execute.

**Comment by vladamx** [comment]
Can you share your AppDelegate, Phone delegate and Carplay delegate?

**Comment by vladamx** [comment]
Solved it - i was trying tho show splash screen in app delegate which breakes the app when launched from carplay screen only and fails silently. 

@ouabing  Thank you

**Comment by vladamx** [comment]
@ouabing Does your js app logic run when you are using CarPlay but your phone screen is off?

**Comment by ouabing** [comment]
@vladamx yes, but the component you register to `AppRegistry` will not render until you start the app

**Comment by vladamx** [comment]
Timers do not work when screen is off. 
So, if you are doing any debouncing on JS side, you need to move it to native.
